### ISSUE TITLE
[CLOSED] 0805 level cannot load lua52.dll

### ISSUE THREAD

**Issue by BlueFinBima** [BlueFinBima/test1#85]
<a href="https://github.com/BlueFinBima"><img src="https://avatars0.githubusercontent.com/u/18526232?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BlueFinBima](https://github.com/BlueFinBima)**
_Tuesday Aug 07, 2018 at 22:26 GMT_
_Originally opened as https://github.com/BlueFinBima/Helios/issues/85_

----

Looks like 
`8/7/2018 4:53:43 PM - All - Helios Version 1.4.2018.805
8/7/2018 4:55:21 PM - Error - Binding threw unhandled exception. (Binding="when Caution Panel YAW SAS on DCS A10C changes set indicator on Indicator 14 to  trigger value")
Exception Source:KeraLua
Exception Message:Unable to load DLL 'lua52': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Stack Trace:
   at KeraLua.NativeMethods.LuaLNewState()
   at NLua.Lua..ctor()
   at GadrocsWorkshop.Helios.HeliosBinding.OnTriggerFired(Object trigger, HeliosTriggerEventArgs e)`
Issued for each binding.

Lua52.dll does not appear in the install directory so this might be another installer issue with the package building in the Release branch.

**Comment by BlueFinBima** [comment]
<a href="https://github.com/BlueFinBima"><img src="https://avatars0.githubusercontent.com/u/18526232?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BlueFinBima](https://github.com/BlueFinBima)**
_Friday Aug 10, 2018 at 11:46 GMT_

----

@yzfanimal 's testing confirms that this issue with the lua52.dll not loading has been resolved by changes to the MSInstaller project in the Release Branch.
